name: Build and Deploy (Hackathon)
on: { workflow_dispatch: {}, push: { branches: [ main ] } }
env: { REGION: us-central1, SERVICE_PREFIX: rc }
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: { contents: read, id-token: write }
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/auth@v2
        with: { credentials_json: ${{ secrets.GCP_SA_KEY }}, project_id: ${{ secrets.GCP_PROJECT_ID }} }
      - uses: google-github-actions/setup-gcloud@v2
      - run: gcloud auth configure-docker $REGION-docker.pkg.dev -q
      - name: Build & push images
        run: |
          REPO=$REGION-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/$SERVICE_PREFIX-repo
          for SVC in ingest_chunker embedder retriever_drafter; do
            docker build -t $REPO/${SVC%_*}:latest services/$SVC
            docker push $REPO/${SVC%_*}:latest
          done
      - name: Terraform init & apply
        working-directory: infra/terraform
        run: |
          terraform init
          terraform apply -auto-approve             -var project_id=${{ secrets.GCP_PROJECT_ID }}             -var region=$REGION
